rule_settings:
  enable: [default]
  disable:
    - replace-interpolation-with-fstring
    - use-fstring-for-concatenation
    - reintroduce-else
    - remove-unnecessary-else
    - assign-if-exp
    - inline-immediately-returned-variable
    - inline-immediately-yielded-variable
    - simplify-len-comparison
    - simplify-empty-collection-comparison
    - remove-redundant-fstring
    - path-read
    - merge-assign-and-aug-assign
    - use-contextlib-suppress
