site_name: "wids Documentation"
site_description: "Documentation for the wids Python library."
site_author: "Your Name"

docs_dir: docs

nav:
  - Home: index.md
  - API: api.md
  - Examples:
      - "Train resnet50 Multiray": examples/train-resnet50-multiray-wds.ipynb
      - "Train resnet50": examples/train-resnet50-wds.ipynb
      - "Column Store": examples/column-store.ipynb
      - "Generate Text Dataset": examples/generate-text-dataset.ipynb
      - "MI Images": examples/mi-images.ipynb
      - "MI Prompts": examples/mi-prompts.ipynb
      - "Run Tesseract": examples/tesseract-wds.ipynb
      - "Train OCR Errors": examples/train-ocr-errors-hf.ipynb
      - "Webdataset Notes": examples/wds-notes.ipynb

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - >
              import os, sys;
              sys.path.insert(0, os.path.join(os.path.abspath('.'), 'src'))
  - mkdocs-jupyter
