# name: Test
# on: [push, pull_request]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-python@v1
#         with:
#           python-version: '3.10'
#       - run: python3 -m pip install invoke pyyaml
#       - run: invoke venv
#       - run: invoke test
